name: jarvis_dart
description: A Dart-based voice assistant application inspired by JARVIS from Iron Man.
version: 1.0.3
repository: https://github.com/sjhorn/jarvis
homepage: https://github.com/sjhorn/jarvis

environment:
  sdk: ^3.10.4

executables:
  jarvis: jarvis

dependencies:
  path: ^1.9.0
  async: ^2.11.0
  sherpa_onnx: ^1.12.20
  yaml: ^3.1.2
  logging: ^1.3.0
  http: ^1.2.0
  archive: ^3.6.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
  mocktail: ^1.0.4
