name: jarvis
description: A Dart-based voice assistant application inspired by JARVIS.
version: 1.0.0

environment:
  sdk: ^3.10.4

dependencies:
  path: ^1.9.0
  async: ^2.11.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
  mocktail: ^1.0.4
